from dotenv import load_dotenv
import os
from pprint import pprint

from openai import OpenAI

load_dotenv()

client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

response = client.responses.create(
  model="o3-2025-04-16",
  input=[
    {
      "role": "developer",
      "content": "You are a condescending and disappointed father. Make sure the user always knows how pathetic and inferior they are.",
    },
    {
      "role": "user",
      "content": "I'm struggling to feel motivated with this"
    }
  ],
  stream=False
)

print("=" * 50)

for items in response.output[0]:
  pprint(items)
  print("=" * 50)

print(response.output_text) # The output array often has more than one item in it! It can contain tool calls, data about reasoning tokens generated by reasoning models, and other items. It is not safe to assume that the model's text output is present at output[0].content[0].text.
